# Configuration for auto-merge bot
# This allows automatic merging of dependency updates that pass all checks

# Merge method to use
merge_method: squash

# Requirements before auto-merging
requirements:
  # All status checks must pass
  status_checks:
    - continuous-integration/travis-ci
    - ci/build
    - ci/test
    - ci/lint
    - ci/type-check
    - security/audit

  # Required approvals (set to 0 for truly automatic merging of patches)
  approvals: 0

# Rules for what can be auto-merged
rules:
  # Auto-merge Dependabot PRs for patch and minor updates
  - match:
      dependency_type: all
      update_type: 'semver:patch'
    allowed: true

  - match:
      dependency_type: all
      update_type: 'semver:minor'
    allowed: true

  # Don't auto-merge major updates
  - match:
      dependency_type: all
      update_type: 'semver:major'
    allowed: false

# Delete branch after merge
delete_branch_after_merge: true

# Comment to post on auto-merged PRs
merge_commit_message: |
  Auto-merged by GitHub Actions

  This PR was automatically merged because:
  - All CI checks passed ✅
  - Only contains patch/minor dependency updates
  - No security vulnerabilities detected
