name: CI Test

on:
  workflow_dispatch:

jobs:
  test:
    name: Quick CI Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type check
        run: pnpm type-check

      - name: Lint
        run: pnpm lint

      - name: Format check
        run: pnpm format:check

      - name: Run unit tests
        run: pnpm test

      - name: Build application
        run: pnpm build
        env:
          DATABASE_URL: 'postgresql://test:test@localhost:5432/test'
          NEXT_PUBLIC_APP_URL: 'http://localhost:3000'
          BETTER_AUTH_SECRET: 'test-secret-for-ci-build-123456789'
          BETTER_AUTH_URL: 'http://localhost:3000'
          PLUNK_API_KEY: 'dummy-key-for-build'
          PLUNK_FROM_EMAIL: 'test@example.com'
          PLUNK_REPLY_TO_EMAIL: 'test@example.com'
          NEXT_PUBLIC_APP_NAME: 'Test App'
          EMAIL_VERIFICATION_REQUIRED: 'false'
          NEXT_PUBLIC_ENABLE_ANALYTICS: 'false'
          NEXT_PUBLIC_ENABLE_SENTRY: 'false'
          SENTRY_SUPPRESS_INSTRUMENTATION_FILE_WARNING: '1'
